<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1578720502967" stop="1578720502967">
  <description>This is the tests collection phase. Failures are modules that failed to collect.</description>
  <name>test_collection_phase</name>
  <title>Collection phase</title>
  <labels/>
  <test-cases>
    <test-case start="1578720502967" status="broken" stop="1578720502967">
      <name>test06_app_article</name>
      <failure>
        <message>failed</message>
        <stack-trace>C:\Users\ACER\AppData\Local\Programs\Python\Python36-32\lib\site-packages\_pytest\python.py:481: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
C:\Users\ACER\AppData\Local\Programs\Python\Python36-32\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
E     File "D:\软件测试资料\就业班第九阶段黑马头条项目实战\day01_项目介绍及UI自动化\UiHMTTAutoItem\scripts\test06_app_article.py", line 15
E       def test_app_article(self,channel=page):
E                                              ^
E   SyntaxError: unexpected EOF while parsing</stack-trace>
      </failure>
      <attachments/>
      <labels/>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
